version: "3"
services:
#  postgres:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    env_file:
#      - .env
#    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
  matrix-bot:
    image: matrix_bot:latest
    container_name: matrix_bot
    volumes:
      - ./nio_store/:/nio_store
      - ./src/:/src
      - ./res/:/res
      - ./data/:/data
      - /var/log/mumble-server/mumble-server.log:/var/log/mumble-server/mumble-server.log
    ports:
      - 8008:8008
    env_file:
      - .env
#    depends_on:
#      - postgres
  filestash:
    container_name: filestash
    image: machines/filestash
    volumes:
      - ./res/:/home/filestash
      - filestash_state:/app/data/state
    restart: always
    ports:
    - "8334:8334"
volumes:
  src:
  nio_store:
  filestash_state:
