version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  matrix-bot:
    image: matrix_bot:latest
    container_name: matrix_bot
    volumes:
      - ./nio_store/:/nio_store
      - ./src/:/src
      - /var/log/mumble-server/mumble-server.log:/var/log/mumble-server/mumble-server.log
    env_file:
      - .env
    depends_on:
      - postgres
volumes:
  src:
  nio_store:
